logging:
  level:
    com.daimler.dmd: DEBUG
    #org.hibernate.type: TRACE
    #org.hibernate.SQL: DEBUG

server:
  port: 8087

spring:
  application:
    name: loans-service

  datasource:
    url: jdbc:postgresql://localhost:5109/loansdb
    username: siya7
    password: Welcome123

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect