logging:
  level:
    com.daimler.dmd: DEBUG
    #org.hibernate.type: TRACE
    #org.hibernate.SQL: DEBUG

server:
  port: 8085

spring:
  application:
    name: loans

  datasource:
    url: jdbc:postgresql://localhost:5432/loansdb
    username: siya7
    password: Welcome123

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: "optional:configserver:http://localhost:8071/"

    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true

  info:
    env:
      enable: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "Eazy Bank Microservices"
    version: "1.0.0"